### PR TITLE
Parse response type with both format and Accept

### PR DESCRIPTION
**Pull request by andrewgaul**
Parse response type with format parameter if present, else the Accept
header, and finally default to text/plain.

### CODE REVIEW

**Comment by andrewgaul** [comment]
Partial fix for running jclouds integration tests against swiftproxy.

**Comment by timuralp** [comment]
:+1:

**Comment by kahing** [comment]
can you also change AccountResource so the two are consistent?

**Comment by andrewgaul** [comment]
Done.

**Comment by kahing** [comment]
:+1:

**Pull request merged**
